export enum TipoArte {
    PINTURA = "PINTURA",
    ESCULTURA = 'ESCULTURA',
    CERÂMICA = 'CERÂMICA',
    FOTOGRAFIA = 'FOTOGRAFIA',
    DESENHO = 'DESENHO',
    VIDEOARTE = 'VIDEOARTE',
    PERFORMANCE = 'PERFORMANCE',
    INSTALAÇÃO = 'INSTALAÇÃO',
    OUTRO = 'OUTRO'
}